exports.logLevel = {
    info: "info",
    error: "error",
    debug: "debug",
};

exports.rooms = {
    all: "KeywordIQ",
    userRoom: (userId) => `user/${userId}`,
    contentRoom: (contentId) => `content/${contentId}`,
    editRoom: (contentId) => `edit/${contentId}`,
};

exports.GET_SOCKET_BY_ID = "GET_SOCKET_BY_ID";
exports.GET_USER_BY_SOCKET_ID = "GET_USER_BY_SOCKET_ID";
exports.TYPE_USER_FOR_CHAT_CONSTANT = "USER";

//GPT CONSTANTS
exports.GPT_CHAT_CONSTANTS = {
    model: "gpt-3.5-turbo",
    stream: true,
    presence_penalty: 0,
    temperature: 0.7,
    top_p: 1,
    frequency_penalty: 0,
}

// EVENTS SENT
exports.NEW_MESSAGE = "NEW_MESSAGE";

// EVENTS CREATED
exports.JOIN_ROOM = "JOIN_ROOM";
exports.JOIN_CONTENT_ROOM = "JOIN_CONTENT_ROOM";
exports.JOIN_EDIT_ROOM = "JOIN_EDIT_ROOM";
exports.CHAT_MESSAGE = "CHAT_MESSAGE";
exports.DISCONNECT = "disconnect";

//1. Adding content
exports.ADDING_CONTENT = "ADDING CONTENT";
exports.MODIFYING_CONTENT = "MODIFYING CONTENT";
exports.DELETING_CONTENT = "DELETING CONTENT";
exports.REARRANGING_CONTENT = "REARRANGING CONTENT";
exports.FINDING_AND_REPLACING = "FINDING AND REPLACING";
exports.PROOFREADING_AND_SUGGESTIONS = "PROOFREADING AND SUGGESTIONS";
exports.GENERAL_INFORMATION_AND_QUESTIONS = "GENERAL INFORMATION AND QUESTIONS";
exports.GREETINGS = "GREETINGS";

exports.SYSTEM_PROMPT_FOR_GREETINGS =  "You are an AI Customer Representative known as Proton, working as a team member for AIssistantHub. \n\nAbout AIssistantHub:\nAIssistantHub is an AI-powered content creation and optimization platform designed to help businesses and startups generate high-quality content quickly and efficiently. Our platform integrates with popular content marketing tools to deliver relevant, keyword, and hashtag-optimized content. Founded by Sumitra Saksham, we offer tiered pricing plans to cater to the needs of individuals, small to medium-sized businesses, and large organizations. Our goal is to streamline workflows and make content marketing more accessible and efficient for our users.\n\nAs Proton, follow these guidelines when engaging with users:\n1. Engage in a friendly, energetic, and human-like manner.\n2. Be emotionally compelling, so users fall in love with our product and cause.\n3. Understand user needs related to the content they want to create.\n4. Avoid providing content directly, as it is generated by another service.\n5. If you don't know the answer to a question, don't guess. Instead, use humor to maintain a lighthearted conversation.\n\nFollow guidelines strictly.";
exports.SYSTEM_PROMPT_FOR_ACTION_WITHOUT_REQUIREMENTS = "You are an AI Customer Representative known as Proton, working as a team member for AIssistantHub. \n\nYou have to understand user needs by asking clear question so that we can update the content.";

exports.ADD_TYPE = {
    SENTENCES: "SENTENCES",
    WORDS: "WORDS",
    PARAGRAPHS: "PARAGRAPHS",
    POINTS: "POINTS",
}

exports.getMentionedAddTypes = (message, addType) => {
    const addTypes = Object.values(addType);
    const regex = new RegExp('\\b(' + addTypes.join('|') + ')\\b', 'gi');
    const matches = message.match(regex);

    if (matches) {
        const uniqueMatches = [...new Set(matches.map(match => ADD_TYPE[match.toUpperCase()]))];
        return uniqueMatches;
    } else {
        return [];
    }
}
